### ISSUE TITLE
Create a separate instance of TelemetryConfiguration

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Azure-Samples/e2e-diagnostic-eventhub-ai-function#5]
Please create a dedicated `TelemetryConfiguration` object so `TelemetryClient` will not inherit any telemetry initializers from the one created by functions' host.

**Comment by SLdragon** [comment]
Fixed : https://github.com/Azure-Samples/e2e-diagnostic-eventhub-ai-function/pull/8
