### ISSUE TITLE
Is there a way to get Timestamp from the logs?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Azure-Samples/e2e-diagnostic-eventhub-ai-function#6]
Set the timestamp to the timestemp when action actually happened, otherwise current time will be used

**Comment by SergeyKanzhelev** [comment]
Note, very old and too new messages will not be accepted by endpoint.

**Comment by SLdragon** [comment]
Thanks, I will fix it

**Comment by SLdragon** [comment]
fixed
https://github.com/Azure-Samples/e2e-diagnostic-eventhub-ai-function/pull/8
